version: "3.10"

services:
  web_app:
    restart: always
    container_name: web_app
    build: ./
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - testdb
      - redis
    command: bash -c "alembic upgrade head && uvicorn core:app --reload --host 0.0.0.0"
    networks:
      - testdb_net
    env_file:
      - ./.env

  db:
    container_name: db
    build:
      context: .
      dockerfile: docker/Dockerfile.db
    ports:
      - "5434:5432"
    networks:
      - testdb_net

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6381:6379"
    env_file:
      - ./.env
    networks:
      - testdb_net

  testdb:
    container_name: testdb
    build:
      context: .
      dockerfile: docker/Dockerfile.testdb
    ports:
      - "5433:5432"
    networks:
      - testdb_net

  test:
    container_name: test
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - testdb_net
    depends_on:
      - testdb



volumes:
  postgres_data:
networks:
  testdb_net:
