version: "3.10"

services:
  redis:
    container_name: redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    image: redis:latest
    restart: always
    ports:
      - "6381:6379"
    env_file:
      - ./.env
    networks:
      - testdb_net

  testdb:
    container_name: testdb
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "testdb" ]
      interval: 10s
      timeout: 5s
      retries: 3
    build:
      context: .
      dockerfile: docker/Dockerfile.testdb
    ports:
      - "5433:5432"
    networks:
      - testdb_net

  test:
    container_name: test
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - testdb_net
    depends_on:
      - testdb



volumes:
  postgres_data:
networks:
  testdb_net:
