version: "3.10"

services:
  web_app:
    restart: on-failure
    container_name: web_app
    build: ./
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    command: bash -c "alembic upgrade head && uvicorn core:app --reload --host 0.0.0.0"
    networks:
      - db_net
    env_file:
      - ./.env

  db:
    container_name: db
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3
    build:
      context: .
      dockerfile: docker/Dockerfile.db
    ports:
      - "5434:5432"
    networks:
      - db_net

  redis:
    container_name: redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    image: redis:latest
    restart: always
    ports:
      - "6381:6379"
    env_file:
      - ./.env
    networks:
      - db_net

volumes:
  postgres_data:
networks:
  db_net:
